const $ = (selector) => document.querySelector(selector);
const state = { tasks: [], saved: JSON.parse(localStorage.getItem('rapi-reports') || '[]') };
const today = new Date();
const iso = (date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 10);
const dateLabel = (value, options = { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }) => new Intl.DateTimeFormat('id-ID', options).format(new Date(`${value}T12:00:00`));

$('#reportDate').value = iso(today);
$('#weekPicker').value = iso(today);
$('#dailyDateLabel').textContent = dateLabel(iso(today), { day: 'numeric', month: 'short' });
$('#reportDate').addEventListener('change', (e) => $('#dailyDateLabel').textContent = dateLabel(e.target.value, { day: 'numeric', month: 'short' }));

function clean(text) { return text.replace(/\s+/g, ' ').replace(/^[-•\d.\s]+/, '').trim(); }
function organization(text) { const known = [['j-trust','J-Trust'],['mandiri taspen','Mandiri Taspen'],['polri','Polri'],['djpp','DJPP'],['pten','PTEN'],['nobu','Bank Nobu'],['internal','Internal'],['ahnlab','AhnLab'],['paa','PAA']]; const found = known.find(([needle]) => text.toLowerCase().includes(needle)); return found ? found[1] : 'Internal'; }
function title(text) { const t = text.toLowerCase(); if (/meeting|bertemu|diskusi/.test(t)) return 'Meeting'; if (/demo|presentasi/.test(t)) return 'Prepare demo'; if (/follow.?up|tindak lanjut/.test(t)) return 'Follow up'; if (/quote|penawaran|vendor/.test(t)) return 'Quote'; if (/dokumen|document/.test(t)) return 'Document'; if (/setup|instal|install/.test(t)) return 'Setup'; if (/belajar|learning/.test(t)) return 'Learning'; if (/event/.test(t)) return 'Event'; if (/kirim|send/.test(t)) return 'Delivery'; return 'Work activity'; }
function recommend(notes) { const sentences = notes.split(/(?:\n|[.!?]+)(?=\s|$)/).map(clean).filter(Boolean); return sentences.slice(0, 8).map((text, i) => ({ status: /menunggu|blocked|tunda/.test(text.toLowerCase()) ? 'On Hold' : 'Complete', time: `${String(9 + i).padStart(2, '0')}:00 - ${String(10 + i).padStart(2, '0')}:00`, task: title(text), detail: text.charAt(0).toUpperCase() + text.slice(1), org: organization(text) })); }
function addRow(task = { status: 'Complete', time: '', task: '', detail: '', org: 'Internal' }) { const fragment = $('#taskRowTemplate').content.cloneNode(true); const row = fragment.querySelector('tr'); row.querySelector('.status-select').value = task.status; row.querySelector('.time-input').value = task.time; row.querySelector('.task-input').value = task.task; row.querySelector('.detail-input').value = task.detail; row.querySelector('.org-input').value = task.org; row.querySelector('.remove-row').onclick = () => row.remove(); $('#taskRows').append(fragment); }
function readRows() { return [...$('#taskRows tr')].map(row => ({ status: row.querySelector('.status-select').value, time: row.querySelector('.time-input').value, task: row.querySelector('.task-input').value, detail: row.querySelector('.detail-input').value, org: row.querySelector('.org-input').value })).filter(t => t.task || t.detail); }
function showDraft(tasks) { $('#emptyDraft').hidden = true; $('#draftArea').hidden = false; $('#taskRows').innerHTML = ''; tasks.forEach(addRow); $('#previewDate').textContent = dateLabel($('#reportDate').value); $('#previewName').textContent = $('#employeeName').value || 'Belum diisi'; $('#taskCount').textContent = `${tasks.length} aktivitas`; }
$('#generateDraft').onclick = () => { const notes = $('#activityNotes').value.trim(); const draft = recommend(notes); if (!draft.length) { $('#activityNotes').focus(); $('#activityNotes').placeholder = 'Masukkan minimal satu aktivitas agar rekomendasi dapat dibuat.'; return; } state.tasks = draft; showDraft(draft); };
$('#loadExample').onclick = () => { $('#activityNotes').value = 'Meeting perkenalan Stealien dan Sparrow ke user. Prepare demo Sparrow untuk Bank J-Trust. Meeting dengan tim Sparrow Korea untuk klarifikasi teknis J-Trust.'; $('#generateDraft').click(); };
$('#addRow').onclick = () => addRow();
function persist() { localStorage.setItem('rapi-reports', JSON.stringify(state.saved)); }
$('#saveDaily').onclick = () => { const tasks = readRows(); if (!tasks.length) return; const report = { id: crypto.randomUUID(), type: 'daily', date: $('#reportDate').value, name: $('#employeeName').value, tasks, savedAt: new Date().toISOString() }; state.saved = state.saved.filter(r => !(r.type === 'daily' && r.date === report.date)).concat(report); persist(); renderArchive(); $('#saveDaily').textContent = 'Tersimpan ✓'; setTimeout(() => $('#saveDaily').textContent = 'Simpan daily report', 1500); };
function monday(dateString) { const d = new Date(`${dateString}T12:00:00`); const day = d.getDay() || 7; d.setDate(d.getDate() - day + 1); return d; }
function weeklyData() { const start = monday($('#weekPicker').value); const end = new Date(start); end.setDate(start.getDate() + 4); const startIso = iso(start), endIso = iso(end); const reports = state.saved.filter(r => r.type === 'daily' && r.date >= startIso && r.date <= endIso).sort((a,b) => a.date.localeCompare(b.date)); const tasks = reports.flatMap(r => r.tasks.map(t => ({...t, date: r.date}))); return { start, end, reports, tasks }; }
$('#generateWeekly').onclick = () => { const {start,end,reports,tasks} = weeklyData(); $('#emptyWeek').hidden = true; $('#weeklyResult').hidden = false; $('#weekTitle').textContent = `${dateLabel(iso(start), {day:'numeric',month:'long'})} - ${dateLabel(iso(end), {day:'numeric',month:'long',year:'numeric'})}`; $('#weeklyRows').innerHTML = tasks.map(t => `<tr><td>${t.status}</td><td>${dateLabel(t.date,{weekday:'short',day:'numeric',month:'short'})}</td><td>${t.task}</td><td>${t.detail}</td><td>${t.org}</td></tr>`).join('') || '<tr><td colspan="5" style="padding:25px;text-align:center;color:#737a74">Belum ada daily report tersimpan pada minggu ini.</td></tr>'; $('#weeklyTaskTotal').textContent = tasks.length; $('#weeklyDaysTotal').textContent = reports.length; $('#weeklyCompleteTotal').textContent = tasks.filter(t => t.status === 'Complete').length; };
$('#saveWeekly').onclick = () => { const {start,end,tasks} = weeklyData(); const report = { id: crypto.randomUUID(), type: 'weekly', date: iso(start), endDate: iso(end), name: $('#employeeName').value, tasks, savedAt: new Date().toISOString() }; state.saved = state.saved.filter(r => !(r.type === 'weekly' && r.date === report.date)).concat(report); persist(); renderArchive(); $('#saveWeekly').textContent = 'Tersimpan ✓'; setTimeout(() => $('#saveWeekly').textContent = 'Simpan weekly report', 1500); };
function renderArchive() { const output = state.saved.slice().sort((a,b) => b.savedAt.localeCompare(a.savedAt)); $('#archiveList').innerHTML = output.length ? output.map(r => `<article class="archive-item"><div><strong>${r.type === 'daily' ? 'Daily report' : 'Weekly report'} - ${r.type === 'weekly' ? `${dateLabel(r.date,{day:'numeric',month:'short'})} - ${dateLabel(r.endDate,{day:'numeric',month:'short',year:'numeric'})}` : dateLabel(r.date)}</strong><span>${r.name || 'Tanpa nama'} · ${r.tasks.length} aktivitas</span></div><span class="archive-type">${r.type.toUpperCase()}</span></article>`).join('') : '<div class="empty-week"><div class="empty-icon">□</div><h3>Arsip masih kosong</h3><p>Report yang Anda simpan akan muncul di sini.</p></div>'; }
document.querySelectorAll('.nav-item').forEach(button => button.onclick = () => { document.querySelectorAll('.nav-item,.view').forEach(el => el.classList.remove('active')); button.classList.add('active'); $(`#${button.dataset.view}View`).classList.add('active'); $('#pageTitle').textContent = button.dataset.view === 'daily' ? 'Daily report' : button.dataset.view === 'weekly' ? 'Weekly report' : 'Arsip report'; });
renderArchive();
