const $ = (selector) => document.querySelector(selector);
const state = { tasks: [], saved: JSON.parse(localStorage.getItem('rapi-reports') || '[]') };
const today = new Date();
const iso = (date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 10);
const dateLabel = (value, options = { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }) => new Intl.DateTimeFormat('id-ID', options).format(new Date(`${value}T12:00:00`));

$('#reportDate').value = iso(today);
$('#weekPicker').value = iso(today);
$('#dailyDateLabel').textContent = dateLabel(iso(today), { day: 'numeric', month: 'short' });
$('#reportDate').addEventListener('change', (e) => $('#dailyDateLabel').textContent = dateLabel(e.target.value, { day: 'numeric', month: 'short' }));

function clean(text) { return text.replace(/\s+/g, ' ').replace(/^[•\-\s]+/, '').replace(/[,\s]+$/, '').trim(); }
function organization(text) { const known = [['j-trust','J-Trust'],['mandiri taspen','Mandiri Taspen'],['polri','Polri'],['djpp','DJPP'],['pten','PTEN'],['nobu','Bank Nobu'],['internal','Internal'],['ahnlab','AhnLab'],['paa','PAA']]; const found = known.find(([needle]) => text.toLowerCase().includes(needle)); return found ? found[1] : 'Internal'; }
function detailRecommendation(description) { const text = description.trim(); const lower = text.toLowerCase(); const org = organization(text); if (/prepare|siapkan/.test(lower)) return `Menyiapkan kebutuhan dan materi untuk ${text.replace(/^(prepare|siapkan)\s*/i, '')}.`; if (/follow.?up/.test(lower)) return `Melakukan tindak lanjut terkait ${text.replace(/^follow.?up\s*/i, '')}.`; if (/meeting|diskusi/.test(lower)) return `Melaksanakan koordinasi dan pembahasan ${text.replace(/^(meeting|diskusi)\s*/i, '')}.`; if (/setup/.test(lower)) return `Melakukan konfigurasi dan verifikasi ${text.replace(/^setup\s*/i, '')}.`; return `Menyelesaikan aktivitas ${text}${org !== 'Internal' ? ` untuk ${org}` : ''}.`; }
function normalizedTime(raw) { const match = raw.trim().match(/^(\d{1,2})(?::(\d{2}))?\s*(?:-|–|sampai)\s*(\d{1,2})(?::(\d{2}))?$/i); if (!match) return raw.trim(); const [, startHour, startMinute = '00', endHour, endMinute = '00'] = match; return `${startHour.padStart(2, '0')}:${startMinute}-${endHour.padStart(2, '0')}:${endMinute}`; }
function recommend(notes) { return notes.split(/\n|,(?=\s*\d{1,2}(?::\d{2})?\s*-)/).map(clean).filter(Boolean).slice(0, 8).map(line => { const match = line.match(/^((?:\d{1,2})(?::\d{2})?\s*(?:-|–|sampai)\s*(?:\d{1,2})(?::\d{2})?)\s+(.+)$/i); const description = match ? clean(match[2]) : line; return { status: /menunggu|blocked|tunda/.test(description.toLowerCase()) ? 'On Hold' : 'Complete', time: match ? normalizedTime(match[1]) : '', description, detail: detailRecommendation(description), org: organization(description) }; }); }
function addRow(task = { status: 'Complete', time: '', description: '', detail: '', org: 'Internal' }) { const fragment = $('#taskRowTemplate').content.cloneNode(true); const row = fragment.querySelector('tr'); row.querySelector('.status-select').value = task.status; row.querySelector('.time-input').value = task.time; row.querySelector('.description-input').value = task.description || task.task || ''; row.querySelector('.detail-input').value = task.detail; row.querySelector('.org-input').value = task.org; row.querySelector('.remove-row').onclick = () => row.remove(); $('#taskRows').append(fragment); }
function readRows() { return [...document.querySelectorAll('#taskRows tr')].map(row => ({ status: row.querySelector('.status-select').value, time: row.querySelector('.time-input').value, description: row.querySelector('.description-input').value, detail: row.querySelector('.detail-input').value, org: row.querySelector('.org-input').value })).filter(t => t.description || t.detail); }
function showDraft(tasks) { $('#emptyDraft').hidden = true; $('#draftArea').hidden = false; $('#taskRows').innerHTML = ''; tasks.forEach(addRow); $('#previewDate').textContent = dateLabel($('#reportDate').value); $('#previewName').textContent = $('#employeeName').value || 'Belum diisi'; $('#taskCount').textContent = `${tasks.length} aktivitas`; prepareDailyDownload(); }
$('#generateDraft').onclick = () => { const notes = $('#activityNotes').value.trim(); const draft = recommend(notes); if (!draft.length) { $('#activityNotes').focus(); $('#activityNotes').placeholder = 'Masukkan minimal satu aktivitas agar rekomendasi dapat dibuat.'; return; } state.tasks = draft; showDraft(draft); };
$('#loadExample').onclick = () => { $('#activityNotes').value = '8-11 prepare sparrow untuk bank j-trust,\n11-12 follow up akun stealthmole untuk polri,\n13-17 meeting sparrow dengan j-trust'; $('#generateDraft').click(); };
$('#addRow').onclick = () => addRow();
function persist() { localStorage.setItem('rapi-reports', JSON.stringify(state.saved)); }
$('#saveDaily').onclick = () => { const tasks = readRows(); if (!tasks.length) return; const report = { id: crypto.randomUUID(), type: 'daily', date: $('#reportDate').value, name: $('#employeeName').value, tasks, savedAt: new Date().toISOString() }; state.saved = state.saved.filter(r => !(r.type === 'daily' && r.date === report.date)).concat(report); persist(); renderArchive(); $('#saveDaily').textContent = 'Tersimpan ✓'; setTimeout(() => $('#saveDaily').textContent = 'Simpan daily report', 1500); };
function pdfSafe(value) { return String(value || '-').replace(/[\\()]/g, '\\$&').replace(/[^\x20-\x7E]/g, '?'); }
function pdfLines(value, width) { const words = pdfSafe(value).split(/\s+/); const lines = []; let line = ''; words.forEach(word => { const next = line ? `${line} ${word}` : word; if (next.length > width && line) { lines.push(line); line = word; } else line = next; }); if (line) lines.push(line); return lines.slice(0, 3); }
function buildPdf(title, subtitle, headers, rows) {
  const pageWidth = 842, pageHeight = 595, margin = 32, colWidths = headers.length === 6 ? [60, 75, 80, 160, 270, 133] : [65, 105, 165, 295, 148];
  const streams = []; let commands = '', y = 555;
  const startPage = () => { commands = '0.13 0.15 0.14 rg\nBT /F2 20 Tf 32 555 Td (' + pdfSafe(title) + ') Tj ET\n0.38 0.42 0.39 rg\nBT /F1 9 Tf 32 538 Td (' + pdfSafe(subtitle) + ') Tj ET\n'; y = 512; };
  const rect = (x, top, width, height, shade) => { commands += `${shade} rg ${x} ${top - height} ${width} ${height} re f\n`; };
  const text = (x, top, value, size = 8, font = 'F1', color = '0.12 0.14 0.13') => { commands += `${color} rg\nBT /${font} ${size} Tf ${x} ${top - size} Td (${pdfSafe(value)}) Tj ET\n`; };
  const header = () => { let x = margin; rect(margin, y, pageWidth - margin * 2, 22, '0.94 0.95 0.91'); headers.forEach((h, i) => { text(x + 5, y - 7, h.toUpperCase(), 7, 'F2', '0.35 0.38 0.35'); x += colWidths[i]; }); y -= 22; };
  startPage(); header();
  rows.forEach(row => { const cellLines = row.map((cell, i) => pdfLines(cell, i === 3 ? 48 : i === 2 ? 20 : 15)); const height = Math.max(...cellLines.map(lines => lines.length)) * 10 + 12; if (y - height < 35) { streams.push(commands); startPage(); header(); } let x = margin; cellLines.forEach((lines, i) => { lines.forEach((line, lineIndex) => text(x + 5, y - 8 - lineIndex * 10, line, 7)); x += colWidths[i]; }); commands += `0.89 0.9 0.87 RG 0.5 w ${margin} ${y - height} ${pageWidth - margin * 2} 0 l S\n`; y -= height; });
  streams.push(commands);
  const objects = ['<< /Type /Catalog /Pages 2 0 R >>', `<< /Type /Pages /Kids [${streams.map((_, i) => `${5 + i * 2} 0 R`).join(' ')}] /Count ${streams.length} >>`, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>', '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'];
  streams.forEach((stream, i) => { objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${6 + i * 2} 0 R >>`); objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}endstream`); });
  let pdf = '%PDF-1.4\n', offsets = [0]; objects.forEach((object, i) => { offsets.push(pdf.length); pdf += `${i + 1} 0 obj\n${object}\nendobj\n`; }); const xref = pdf.length; pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map(offset => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return new Blob([pdf], { type: 'application/pdf' });
}
function setDownloadLink(link, filename, title, subtitle, headers, rows) { if (link.dataset.pdfUrl) URL.revokeObjectURL(link.dataset.pdfUrl); const url = URL.createObjectURL(buildPdf(title, subtitle, headers, rows)); link.href = url; link.download = filename; link.dataset.pdfUrl = url; }
function prepareDailyDownload() { const tasks = readRows(); if (!tasks.length) return; setDownloadLink($('#downloadDaily'), `Daily Report - ${$('#reportDate').value}.pdf`, 'DAILY REPORT', `${$('#employeeName').value} | ${dateLabel($('#reportDate').value)}`, ['Status', 'Jam', 'Description', 'Detail', 'Organization'], tasks.map(t => [t.status, t.time, t.description, t.detail, t.org])); }
$('#taskRows').addEventListener('input', prepareDailyDownload);
$('#taskRows').addEventListener('change', prepareDailyDownload);
function monday(dateString) { const d = new Date(`${dateString}T12:00:00`); const day = d.getDay() || 7; d.setDate(d.getDate() - day + 1); return d; }
function weeklyData() { const start = monday($('#weekPicker').value); const end = new Date(start); end.setDate(start.getDate() + 4); const startIso = iso(start), endIso = iso(end); const reports = state.saved.filter(r => r.type === 'daily' && r.date >= startIso && r.date <= endIso).sort((a,b) => a.date.localeCompare(b.date)); const tasks = reports.flatMap(r => r.tasks.map(t => ({...t, date: r.date}))); return { start, end, reports, tasks }; }
$('#generateWeekly').onclick = () => { const {start,end,reports,tasks} = weeklyData(); $('#emptyWeek').hidden = true; $('#weeklyResult').hidden = false; $('#weekTitle').textContent = `${dateLabel(iso(start), {day:'numeric',month:'long'})} - ${dateLabel(iso(end), {day:'numeric',month:'long',year:'numeric'})}`; $('#weeklyRows').innerHTML = tasks.map(t => `<tr><td>${t.status}</td><td>${dateLabel(t.date,{weekday:'short',day:'numeric',month:'short'})}</td><td>${t.time || '-'}</td><td>${t.description || t.task || '-'}</td><td>${t.detail}</td><td>${t.org}</td></tr>`).join('') || '<tr><td colspan="6" style="padding:25px;text-align:center;color:#737a74">Belum ada daily report tersimpan pada minggu ini.</td></tr>'; $('#weeklyTaskTotal').textContent = tasks.length; $('#weeklyDaysTotal').textContent = reports.length; $('#weeklyCompleteTotal').textContent = tasks.filter(t => t.status === 'Complete').length; if (tasks.length) setDownloadLink($('#downloadWeekly'), `Weekly Report - ${iso(start)}.pdf`, 'WEEKLY REPORT', `${$('#employeeName').value} | ${dateLabel(iso(start), {day:'numeric',month:'long'})} - ${dateLabel(iso(end), {day:'numeric',month:'long',year:'numeric'})}`, ['Status', 'Tanggal', 'Jam', 'Description', 'Detail', 'Organization'], tasks.map(t => [t.status, dateLabel(t.date, {day:'numeric',month:'short'}), t.time, t.description || t.task, t.detail, t.org])); };
$('#saveWeekly').onclick = () => { const {start,end,tasks} = weeklyData(); const report = { id: crypto.randomUUID(), type: 'weekly', date: iso(start), endDate: iso(end), name: $('#employeeName').value, tasks, savedAt: new Date().toISOString() }; state.saved = state.saved.filter(r => !(r.type === 'weekly' && r.date === report.date)).concat(report); persist(); renderArchive(); $('#saveWeekly').textContent = 'Tersimpan ✓'; setTimeout(() => $('#saveWeekly').textContent = 'Simpan weekly report', 1500); };
function renderArchive() { const output = state.saved.slice().sort((a,b) => b.savedAt.localeCompare(a.savedAt)); $('#archiveList').innerHTML = output.length ? output.map(r => `<article class="archive-item"><div><strong>${r.type === 'daily' ? 'Daily report' : 'Weekly report'} - ${r.type === 'weekly' ? `${dateLabel(r.date,{day:'numeric',month:'short'})} - ${dateLabel(r.endDate,{day:'numeric',month:'short',year:'numeric'})}` : dateLabel(r.date)}</strong><span>${r.name || 'Tanpa nama'} · ${r.tasks.length} aktivitas</span></div><span class="archive-type">${r.type.toUpperCase()}</span></article>`).join('') : '<div class="empty-week"><div class="empty-icon">□</div><h3>Arsip masih kosong</h3><p>Report yang Anda simpan akan muncul di sini.</p></div>'; }
document.querySelectorAll('.nav-item').forEach(button => button.onclick = () => { document.querySelectorAll('.nav-item,.view').forEach(el => el.classList.remove('active')); button.classList.add('active'); $(`#${button.dataset.view}View`).classList.add('active'); $('#pageTitle').textContent = button.dataset.view === 'daily' ? 'Daily report' : button.dataset.view === 'weekly' ? 'Weekly report' : 'Arsip report'; });
renderArchive();
